### PR TITLE
Vue 3 Port

### PR DESCRIPTION
**Pull request by crutchcorn**
This is as 1:1 of a port I can do in Vue 3.

I know in initial discussions with #25, there was the idea to change other code - however, I felt this was a good migration for my more immediate needs.

Let me know if there's anything else I can do. I am using this exact code in production currently

### CODE REVIEW

**Comment by EvodiaAut** [comment]
@crutchcorn Great work!

I will have a look at it this week and in the best case release a V2.
Important are still the events see #7 [(code line)](https://github.com/EvodiaAut/vue-marquee-text-component/pull/40/files#diff-5f5b0589edb824f245f79538dd2ae2c082ad637d31cc288f03b523e07979b82bL37)

**Comment by crutchcorn** [comment]
So actually I was curious about that as well. 

Even with that LOC removed, the hover-to-pause still appears to work with this code I ported.

I looked through a lot of Vue's source code and all of their TS definitions and couldn't find an instance of `on` within a component instance for Vue 3.

However, `on` in Vue 2 seems to've bound events from an element created with `h`. It seems like Vue 3 may simply rely on event bubbling.

**Comment by EvodiaAut** [comment]
It looks like you don't have the best solution yourself yet.
https://github.com/vuejs/rfcs/blob/master/active-rfcs/0008-render-function-api-change.md#escape-hatches-for-explicit-binding-types

For me it was important that not every single element triggers an event but only the parent.

**Comment by crutchcorn** [comment]
> For me it was important that not every single element triggers an event but only the parent.

See, I'm not confident that's not happening right now, though.

I changed the example to:

```
  <marquee-text
          :repeat="3"
          :paused="isPaused"
          class="py-2 bg-dark text-white mt-2"
          @mouseenter="isPaused = !isPaused; log('mouseenter')"
          @mouseleave="isPaused = false; log('mouseleave')"
        >
```

> `log` shown here is a method that just `console.log` the event running

And the logs for the events don't seem to duplicate:

run_once

I'm clearly running my mouse over multiple different elements as children, aren't I? If it bubbled/captured _every_ event, wouldn't it log more than twice?

**Comment by EvodiaAut** [comment]
See #25

**Pull request merged**
